# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fo-wwRnD98VHgPDwf13IwjhQzrVSU7FA
"""

import matplotlib.pyplot as plt
import numpy as np

# make the data
np.random.seed(3)
x = 4 + np.random.normal(0, 2, 24)
y = 4 + np.random.normal(0, 2, len(x))
# size and color:
sizes = np.random.uniform(15, 80, len(x))
colors = np.random.uniform(15, 80, len(x))

# plot
fig, ax = plt.subplots()

ax.scatter(x, y, s=sizes, c=colors, vmin=0, vmax=100)

ax.set(xlim=(0, 8), xticks=np.arange(1, 8),
       ylim=(0, 8), yticks=np.arange(1, 8))

plt.show()

import matplotlib.pyplot as plt
import numpy as np
# make data
x = np.linspace(0, 10, 100) #linspace funksiyasi kesmani bo’laklarga bo’ladi
print(x)
y = 4 + 2 * np.sin(2 * x)
print (y)
# plot
fig, ax = plt.subplots() #platformani yaratish
ax.plot(x, y, linewidth=2.0)
plt.show()